# Generated by Django 2.2 on 2019-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter_api', '0002_auto_20191118_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Openings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expired_on', models.DateTimeField()),
                ('image', models.URLField(default='', max_length=255)),
                ('experience', models.FloatField(default=0)),
                ('skills', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('contact_mail', models.EmailField(max_length=255)),
                ('location', models.CharField(max_length=50)),
                ('website', models.URLField(default='', max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('company_logo', models.URLField(max_length=255)),
            ],
        ),
    ]
